---
# ==============================================================================
# TP Administration Systèmes - Playbook Ansible
# Université de Yaoundé I - Licence 3 Informatique - INF 3611
# ==============================================================================

- name: "Création automatisée des utilisateurs étudiants"
  hosts: students_servers
  become: yes
  gather_facts: yes
  vars_files:
    - "users.yml"
    - "group_vars/all.yml"
  
  vars:
    student_group: "students-inf-361"
    disk_limit_gb: 15
    ram_limit_percent: 20
    default_shell: "/bin/bash"
    welcome_message: |
      ========================================================================
      BIENVENUE SUR LE SERVEUR DE TP
      ========================================================================
  
  pre_tasks:
    - name: "Vérifier la connexion au serveur"
      ping:
    
    - name: "Installer les dépendances système"
      package:
        name:
          - python3
          - python3-pip
          - quota
          - openssl
        state: present
      when: ansible_os_family == 'Debian'
    
    - name: "Installer les dépendances (RHEL)"
      yum:
        name:
          - python3
          - python3-pip
          - quota
          - openssl
        state: present
      when: ansible_os_family == 'RedHat'
  
  tasks:
    - name: "Créer le groupe principal"
      group:
        name: "{{ student_group }}"
        state: present
    
    - name: "Créer les utilisateurs"
      include_tasks: "roles/student_users/tasks/create_single_user.yml"
      loop: "{{ students }}"
      loop_control:
        loop_var: student
        label: "{{ student.username }}"
    
    - name: "Configurer les quotas disque"
      include_tasks: "roles/student_users/tasks/setup_quotas.yml"
    
    - name: "Restreindre la commande su"
      copy:
        dest: "/etc/sudoers.d/no-su-{{ student_group }}"
        content: |
          # Empêcher l'utilisation de 'su' par le groupe {{ student_group }}
          %{{ student_group }} ALL=(ALL) ALL, !/bin/su, !/usr/bin/su
        validate: "/usr/sbin/visudo -cf %s"
        mode: "0440"
      when: restrict_su | default(true)
    
    - name: "Envoyer les emails de notification"
      include_tasks: "tasks/send_emails.yml"
      when: smtp_username is defined and smtp_password is defined
  
  post_tasks:
    - name: "Afficher le résumé"
      debug:
        msg: |
           Exécution terminée !
           Utilisateurs créés: {{ students | length }}
            Groupe: {{ student_group }}
           Log: /var/log/ansible/user_creation.log